module.exports = {
  horarios: [
    "horario",
    "horarios",
    "abre",
    "fecha",
    "ate que horas",
    "que horas",
    "de manha",
    "de tarde",
    "de noite",
    "atende de noite",
  ],
  telefone: [
    "telefone",
    "contato",
    "numero",
    "ligar",
    "ligacao",
    "telefone pra contato",
  ],
  localizacao: [
    "endereco",
    "localizacao",
    "onde fica",
    "onde e",
    "como chegar",
  ],
  filiacao: [
    "filiar",
    "filiacao",
    "cadastrar",
    "cadastro",
    "como entrar",
    "como participar",
    "como faço pra me filiar",
  ],
  direitos: ["direitos", "salario", "carreira", "beneficios", "ajuda", "apoio"],
  assessoria_juridica: ["juridica", "juridico", "processo administrativo", "processos administrativos", "defesa legal", "apoio juridico"],
  atendimento: [
    "atendimento",
    "atendente",
    "suporte",
    "ajuda",
    "falar com alguem",
    "falar com pessoa",
  ],
  descricao: ["sobre", "o que e", "quem e", "explicacao", "como funciona"],
};
